#!/bin/zsh
# -*- coding: utf-8 -*-

##
# Z shell INITIALIZATION FILE
##

##
# NOTICE:
#   Launched as login shell
#     1) ~/.zshenv
#     2) ~/.zprofile
#     3) ~/.zshrc
#     4) ~/.zlogin
#   Launched as interactive shell (not as login shell)
#     1) ~/.zshenv
#     2) ~/.zshrc
#   Execute zsh script
#     1) ~/.zshenv
#   Logout zsh launched as login shell
#     1) ~/.zlogout
##

zsh_initdir=~/.zsh

zsh_path=${zsh_initdir}/path.zshrc
zsh_shell=${zsh_initdir}/shell.zshrc
zsh_aliases=${zsh_initdir}/aliases.zshrc
zsh_completions=${zsh_initdir}/completions.zshrc
zsh_environment=${zsh_initdir}/environment.zshrc


if [ -r ${zsh_path} ]; then 
    source ${zsh_path}
fi

if [ -r ${zsh_shell} ]; then
    source ${zsh_shell}
fi

if [ -r ${zsh_aliases} ]; then
    source ${zsh_aliases}
fi

if [ -r ${zsh_completions} ]; then
    source ${zsh_completions}
fi

if [ -r ${zsh_environment} ]; then
    source ${zsh_environment}
fi


host=`hostname`
host=`echo $host | tr A-Z a-z`

user=`whoami`

export HOST="${host}"
export USER="${user}"

# User ID
if [ -z $uid ]; then
    uid=`id | cut -d = -f 2 | cut -d \( -f 1`
fi

# MISCELLANEOUS SETS
if [ -z $version ]; then
    verion="unknown"
fi

# Non-root users
if [ ! $uid ]; then
    unset autologout
else
  # Avoid closing of Terminal windows when logged in as root
    if [ -n "${TERM_PROGRAM}" -a -n "${SHLVL}" ]; then
	    if [ "$SHLVL" -eq "1" ]; then
	        unset autologout
	    fi
    fi
fi

# import site configurations
if [ -r ${HOME}/.site-zshrc ]; then
    source ${HOME}/.site-zshrc
fi
